### PR TITLE
Convert contracts to depend on open zeppelin 

### PR DESCRIPTION
**Pull request by tarrencev**
Hi!

I converted the contracts to depend on the open zeppelin ERC20 implementations. Not sure if that is of interest to you but thought I'd open a PR just incase :)

Thanks a lot for the bonding curve implementation, its very well done!

### CODE REVIEW

**Comment by oed** [comment]
Hey, thanks for this!
Definitely simplifies things to only require the zeppelin library. Does this change how much gas is required to deploy a curve? If so in which direction?

**Comment by tarrencev** [comment]
No problem!

Ran a quick benchmark on deploy costs, it does increase deploy costs:

`EthPolynomialCurvedToken`: `1368752 -> 1857195`, `~36% increase`
`PolynomialCurvedToken`: `2029321 -> 1540810`, `~32% increase`

For me thats not a big deal, since it's a once-off cost and when deploying multiple curves I'd probably use a proxy pattern.

**Comment by oed** [comment]
Thanks! Yeah that's a good point. The contract probably need to be modified to support the proxy pattern if I'm not mistaken?

**Comment by tarrencev** [comment]
It would require a separate initialization function. I would extend this contract to expose that functionality, rather than bake it into these base contracts. Happy to add a Proxy interface if you'd like

**Comment by oed** [comment]
That would be awesome! 
I'm trying to test the your branch currently but seems like I can't find the `openzeppelin-solidity` package when I do `truffle install`. Am I missing anything?

**Comment by tarrencev** [comment]
Ok will do!

Right now, it's being installed using npm, so try an `npm install`.

**Comment by oed** [comment]
Right I see thanks. Do you know if there a difference between `openzeppelin-solidity` from npm and `zeppelin` from ethpm?

**Review by oed — APPROVED** [review]

**Comment by oed** [comment]
Tnx for the PR, merging 😄

**Pull request merged**
