### PR TITLE
Migrate to Bancors Power Function

### PR DESCRIPTION
**Pull request by tarrencev**
This migrates the integral to bancors power function, which will enable us to implement more expressive curves (i.e. logarithmic curves).

### CODE REVIEW

**Comment by oed** [comment]
This is great, thank you 🎉 
Sorry for the slow response, I've been of-grid the last week. I'll make sure to take some time to review this this week!

**Comment by tarrencev** [comment]
No worries!

I think this commit still needs some work. It seems certain parameterizations fall outside the bounds of what Bancors power function can handle. Still working on better understanding the implementation, let me know if you have any feedback.

**Comment by oed** [comment]
Hey @tarrencev had a look though the code. Looks pretty good. Again I'm wondering what the gas difference is, but my guess is that the difference isn't that big.
Currently you can only specify the exponent as the numerator to the power function. This allows us to create super linear and linear curves. If we add the ability to also configure the denominator we could allow the creation of sub linear curves as well. That would be sweet :)

**Comment by tarrencev** [comment]
Hey @oed, thanks for taking a look. I'm not sure on the gas cost differences, although I dont think it would change much. Sub linear curves is definitely what I am interested in!

I've played around with this implementation a bit and I don't think is ideal. The numbers go out-of-bounds w.r.t the Power functions capabilities pretty quickly (since the base, token supply, is so large). I think we might need to play around with the parameterization of generator code or reparameterize the function to be more similar to how Bancor does it. I took a swing at that here: https://github.com/tarrencev/curve-bonded-tokens

**Comment by oed** [comment]
Yeah, I'm not a super big fan of the bancor code. Mostly because it's so difficult to read. I've mostly put of my bonding curve experiments until the fixed point types gets merged into solidity (v0.5.1 earliest).

**Pull request closed without merging**
